all: src/POOCasino.class
src/POOCasino.class:src/POOCasino.java
	javac -d ./lib src/*.java -cp lib
clean:
	rm lib/PlayerB02705010.class
	rm lib/POOCasino.class
	rm -rf lib/assignment4
run:
	java -cp lib POOCasino 100 200000
